path = [
  "/opt/homebrew/bin",
  "/usr/local/bin",
  "/Users/ereslibre/.bin",
  "/Users/ereslibre/.cargo/bin",
  "/Users/ereslibre/.ghcup/bin",
  "/Users/ereslibre/.nix-profile/bin",
  "/Users/ereslibre/go/bin",
  "/usr/bin",
  "/bin",
  "/usr/sbin",
  "/sbin",
]

startup = [
  "alias k = ^kubectl",
  "alias ll = ls -l",
  "alias la = ls -a",
  "alias nuopen = open",
  "alias open = ^open",
]

skip_welcome_message = true

[env]
EDITOR = "emacs"
NIX_PATH = "nixpkgs=/Users/ereslibre/.nix-defexpr/channels/nixpkgs"

[line_editor]
edit_mode = "emacs"
