name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Format
        run: |
          make fmt
          git diff --exit-code
  activate-machine:
    strategy:
      matrix:
        include:
          - os: macos-12
            user: ereslibre
            host: Rafaels-Air
          - os: ubuntu-latest
            user: ereslibre
            host: nuc-1
          - os: ubuntu-latest
            user: ereslibre
            host: nuc-2
          - os: ubuntu-latest
            user: ereslibre
            host: nuc-3
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Configure cachix
        uses: cachix/cachix-action@v12
        with:
          name: workstations
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Activate
        env:
          ACTIVATION_USER: ${{ matrix.user }}
          ACTIVATION_HOST: ${{ matrix.host }}
          HOME_MANAGER_BACKUP_EXT: hm-bak
        run: |
          make activate-user-at-host
