name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Setup the magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Format
        run: |
          make fmt
          git diff --exit-code
  flake-check:
    name: Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        user: [ereslibre]
        host: [hulk, nuc-1, nuc-2, nuc-3]
        include:
          - os: macos-latest
            user: ereslibre
            host: Rafaels-Air
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Setup the magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build
        run: |
          # Force the creation of the profile dir
          nix profile list
          # Build
          make build \
            ACTIVATION_USER=${{ matrix.user }} \
            ACTIVATION_HOST=${{ matrix.host }}
