name: CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Format
        run: |
          make fmt
      - name: Lint
        run: |
          make lint
          git diff --exit-code
  activate-Rafaels-MacBook-Air:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Activate
        env:
          ACTIVATION_USER: ereslibre
          ACTIVATION_HOST: Rafaels-MacBook-Air
          HOME_MANAGER_BACKUP_EXT: backup
        run: |
          make activate-user-at-host
  activate-desktop:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Activate
        env:
          ACTIVATION_USER: ereslibre
          ACTIVATION_HOST: desktop
          HOME_MANAGER_BACKUP_EXT: backup
        run: |
          make activate-user-at-host
